CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE imports (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "eersteToelatingDatum" timestamp with time zone NOT NULL,
    "totaalImport" integer NOT NULL,
    "importSeconden" numeric NOT NULL,
    CONSTRAINT "PK_imports" PRIMARY KEY (id)
);

CREATE TABLE merken (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    naam character varying(50) NOT NULL,
    CONSTRAINT "PK_merken" PRIMARY KEY (id)
);

CREATE TABLE "voertuigSoorten" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    naam text NOT NULL,
    CONSTRAINT "PK_voertuigSoorten" PRIMARY KEY (id)
);

CREATE TABLE handelsbenamingen (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    naam character varying(50) NOT NULL,
    "merkId" integer NOT NULL,
    CONSTRAINT "PK_handelsbenamingen" PRIMARY KEY (id),
    CONSTRAINT "FK_handelsbenamingen_merken_merkId" FOREIGN KEY ("merkId") REFERENCES merken (id) ON DELETE CASCADE
);

CREATE TABLE voertuigen (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    kenteken character varying(10) NOT NULL,
    "voertuigSoortId" integer NOT NULL,
    "merkId" integer NOT NULL,
    "handelsbenamingId" integer NOT NULL,
    "vervalDatumAPK" timestamp with time zone NULL,
    tenaamstelling timestamp with time zone NOT NULL,
    "eersteToelating" timestamp with time zone NOT NULL,
    inrichting character varying(50) NULL,
    kleur character varying(50) NULL,
    "massaLedig" numeric NULL,
    "importId" integer NOT NULL,
    CONSTRAINT "PK_voertuigen" PRIMARY KEY (id),
    CONSTRAINT "FK_voertuigen_handelsbenamingen_handelsbenamingId" FOREIGN KEY ("handelsbenamingId") REFERENCES handelsbenamingen (id) ON DELETE CASCADE,
    CONSTRAINT "FK_voertuigen_imports_importId" FOREIGN KEY ("importId") REFERENCES imports (id) ON DELETE CASCADE,
    CONSTRAINT "FK_voertuigen_merken_merkId" FOREIGN KEY ("merkId") REFERENCES merken (id) ON DELETE CASCADE,
    CONSTRAINT "FK_voertuigen_voertuigSoorten_voertuigSoortId" FOREIGN KEY ("voertuigSoortId") REFERENCES "voertuigSoorten" (id) ON DELETE CASCADE
);
COMMENT ON COLUMN voertuigen.kleur IS 'Hier staat de kleur.';

CREATE INDEX "IX_handelsbenamingen_merkId" ON handelsbenamingen ("merkId");

CREATE INDEX "IX_voertuigen_handelsbenamingId" ON voertuigen ("handelsbenamingId");

CREATE INDEX "IX_voertuigen_importId" ON voertuigen ("importId");

CREATE INDEX "IX_voertuigen_merkId" ON voertuigen ("merkId");

CREATE INDEX "IX_voertuigen_voertuigSoortId" ON voertuigen ("voertuigSoortId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220215205220_Initieel', '6.0.2');

COMMIT;

